# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-20 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceAttempts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=b'faceattempt/')),
            ],
        ),
        migrations.AlterField(
            model_name='voter',
            name='MiddleName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
